# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Favicheck < Formula
  desc "Detect a site's web framework from their favicon using the OWASP common favicons database"
  homepage "https://github.com/szTheory/favicheck"
  version "0.1.1"
  license "BSD"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/szTheory/favicheck/releases/download/v0.1.1/favicheck_0.1.1_Darwin_arm64.tar.gz"
      sha256 "824f359f318b74f79b62dbf4cd8abc81d887cc02a355223d1279683b1b869cd0"

      def install
        bin.install "favicheck"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/szTheory/favicheck/releases/download/v0.1.1/favicheck_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "74e459cc743fddbe3ce9a476b8cf282c6b858210c15b3545d9c29de3d5370e6b"

      def install
        bin.install "favicheck"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/szTheory/favicheck/releases/download/v0.1.1/favicheck_0.1.1_Linux_x86_64.tar.gz"
      sha256 "7ab3537a82a3b80f82e63b2fe78b72aecd65038ce38859704df9b7a376c05bad"

      def install
        bin.install "favicheck"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/szTheory/favicheck/releases/download/v0.1.1/favicheck_0.1.1_Linux_arm64.tar.gz"
      sha256 "9d5ca3939b611915cf1549000f2e21cbfd66beb0e21c55ad77abe9ee905e1598"

      def install
        bin.install "favicheck"
      end
    end
  end

  test do
    system "#{bin/favicheck}"
  end
end
